services:
  - type: web
    name: portfolio-rodarena
    env: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
